Repository theozebua/oze-framework, pull requests merged in 2022-12, with the labels that each got.

#4 Use App class to wrap the application
  app/Controllers/HomeController.php
  bootstrap/app.php
  composer.json
  composer.lock
  config/path.php
  helpers/path.php
  helpers/view.php
  public/index.php
  routes/web.php
Labels: enhancement

#6 Use database wrapper
  app/Models/User.php
  composer.lock
  config/database.php
Labels: enhancement

#8 Use view helper functions
  app/Controllers/HomeController.php
  composer.lock
Labels: enhancement

#9 Setup the application with environment variables
  .env.example
  .gitignore
  composer.lock
  config/database.php
  public/index.php
Labels: enhancement

#10 Use env helper functions
  composer.lock
  config/database.php
Labels: enhancement

#11 Update dependencies
  composer.lock
Labels: enhancement

#13 chore: minimum PHP version on composer
  composer.json
  composer.lock
Labels: adjustment

#14 fix: empty db password error
  config/database.php
Labels: fixed

#15 Update dependencies
  app/Models/User.php
  composer.lock
Labels: enhancement, adjustment

#17 Update dependencies
  app/Models/User.php
  composer.lock
Labels: adjustment

#18 Update dependencies
  composer.lock
Labels: enhancement, adjustment

#19 Update dependencies
  composer.lock
Labels: adjustment

#20 Create the application serve file
  oze
  public/favicon.ico
Labels: enhancement
